import asyncio
import logging
from datetime import datetime, timezone, timedelta
from typing import Optional, Dict, Any

from client import POClient
from streaming_client import StreamingClient
from config import settings

logger = logging.getLogger(__name__)


class TradingBot:
    def __init__(self, client: POClient, streaming_client: StreamingClient):
        self.client = client
        self.streaming_client = streaming_client
        self._running = False
        self._ready = False
        self._current_asset = settings.trade_asset
        self._signal_task: Optional[asyncio.Task] = None

        # Risk state (martingale)
        self.stake = settings.base_stake
        self.consecutive_losses = 0
        self.daily_pnl = 0.0
        self._last_day = datetime.now(timezone.utc).date()

        # Stats
        self.balance = 0.0
        self.total_pnl = 0.0
        self.wins = 0
        self.losses = 0
        self.trade_history: list = []

        # Connection
        self._connected = False
        self._data_task: Optional[asyncio.Task] = None
        self._update_interval = 0.5

    async def connect(self) -> bool:
        if self._connected:
            return True

        if not await self.client.connect():
            return False

        if not await self.streaming_client.connect():
            logger.error("Streaming client failed to connect")
            await self.client.disconnect()
            return False

        # Start streaming once (it will run continuously)
        await self.streaming_client.start_streaming(self._on_signal)

        self._connected = True
        self._data_task = asyncio.create_task(self._data_update_loop())
        self._ready = True
        logger.info(f"Connected. Streaming active for {self._current_asset}.")
        return True

    async def disconnect(self):
        self._connected = False
        self._running = False
        if self._data_task:
            self._data_task.cancel()
        await self.streaming_client.disconnect()
        await self.client.disconnect()
        logger.info("Disconnected")

    async def _data_update_loop(self):
        while self._connected:
            try:
                await self.client.refresh_balance()
                self.balance = self.client.balance
                await asyncio.sleep(self._update_interval)
            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"Data update error: {e}")
                await asyncio.sleep(1)

    async def start_trading(self):
        if not self._connected:
            logger.error("Cannot start trading: not connected")
            return
        if self._running:
            return
        if not self._ready:
            logger.warning("Bot not ready")
            return
        self._running = True
        # Enable signals – the streaming client will wait for the next full candle
        self.streaming_client.enable_signals()
        logger.info("Trading started (signals enabled, waiting for next candle).")

    async def stop_trading(self):
        self._running = False
        self.streaming_client.disable_signals()
        logger.info("Trading stopped (signals disabled).")

    async def _on_signal(self, signal_data: Dict[str, Any]):
        """Called when a signal is generated by the streaming client."""
        if not self._running:
            logger.debug("Signal received but trading is paused")
            return

        direction = signal_data["direction"]
        asset = signal_data["symbol"]
        open_price = signal_data["open"]
        current_price = signal_data["current"]
        timestamp = signal_data["timestamp"]

        logger.info(
            f"💹 TRADE SIGNAL: {direction} on {asset} | "
            f"Open: {open_price:.5f} | Current: {current_price:.5f}"
        )

        # Place the trade
        result = await self.client.place_trade(
            asset,
            direction,
            self.stake,
            settings.trade_duration,  # 30 seconds
            check_win=True,
        )

        if result:
            trade_id = result.get("id")
            win = result.get("result") == "win"
            try:
                profit = float(result.get("profit", 0.0))
            except (ValueError, TypeError):
                profit = 0.0

            trade = {
                "id": trade_id,
                "asset": asset,
                "direction": direction,
                "stake": self.stake,
                "open_time": datetime.now(timezone.utc).isoformat(),
                "result": "WIN" if win else "LOSS",
                "pnl": profit if win else -abs(profit),
            }
            self.trade_history.insert(0, trade)
            if len(self.trade_history) > 100:
                self.trade_history.pop()

            self.total_pnl += trade["pnl"]
            self.daily_pnl += trade["pnl"]

            if win:
                self.wins += 1
                self.stake = settings.base_stake
                self.consecutive_losses = 0
            else:
                self.losses += 1
                self.consecutive_losses += 1
                self.stake = min(self.stake * settings.multiplier, settings.max_stake)
                if self.consecutive_losses >= settings.max_consecutive_losses:
                    self.reset_martingale()

            logger.info(
                f"✅ TRADE RESULT: {trade['result']} | "
                f"{direction} {asset} | Stake: ${self.stake:.2f} | "
                f"P&L: {trade['pnl']:.2f}"
            )
            await self.client.refresh_balance()
            self.balance = self.client.balance
        else:
            logger.error("❌ Trade placement failed – no result returned")

    def reset_martingale(self):
        self.stake = settings.base_stake
        self.consecutive_losses = 0
        logger.info("🔄 Martingale reset")

    def get_stats(self) -> Dict[str, Any]:
        total = self.wins + self.losses
        win_rate = (self.wins / total * 100) if total > 0 else 0.0
        return {
            "balance": self.balance,
            "total_pnl": self.total_pnl,
            "daily_pnl": self.daily_pnl,
            "win_rate": round(win_rate, 2),
            "consecutive_wins": 0,
            "consecutive_losses": self.consecutive_losses,
            "current_stake": self.stake,
            "current_asset": self._current_asset,
            "trades": self.trade_history[:20],
            "candle": {},
            "connected": self._connected,
            "ready": self._ready,
            "running": self._running,
        }

    def reset_stats(self):
        self.stake = settings.base_stake
        self.consecutive_losses = 0
        self.daily_pnl = 0.0
        self.balance = 0.0
        self.total_pnl = 0.0
        self.wins = 0
        self.losses = 0
        self.trade_history = []